
import type { InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.scss'
import {Menu,MenuItem} from '../components/Menu'

import {createClient} from 'contentful'
import { homeProps } from '../framework/common/types/webpage'
import Navbar from '../components/Navbar/Navbar'




const Home: NextPage<homeProps> = ({topBar,menu,iconLibrary}) => {


  const topItems = topBar
  const menuItems= menu
  const Icon =iconLibrary

  
  const mainIcon= Icon.filter( (a)=>{return a.fields.name==='mainIcon'})[0].fields.icon.fields.file.url 
  const heroImage= null//Icon.filter( (a)=>{return a.fields.name==='heroImage'})[0].fields.icon.fields.file.url 
  const hamburgerMenu= Icon.filter( (a)=>{return a.fields.name==='hamburgerMenu'})[0].fields.icon.fields.file.url 
  console.log(mainIcon)
  console.log(heroImage)
  console.log(hamburgerMenu)
  topItems.sort( (a,b) => {
    return a.fields.id - b.fields.id })
  
  return (
   <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
          
          <Navbar topItems={topItems} /> 
          
          <div >
          
              <div >
                <div >
                {mainIcon &&
                  <Image src={`https:${mainIcon}` } alt="Tadeo Logo" width={200} height={60} />}
                </div>
               
                  <Menu>   
                    {menuItems.filter((a)=> {return a.fields.position === 'Left'}).map((e,i) => (
                    <MenuItem key={i}  href={e.fields.link} isActive={true} > {e.fields.name} </MenuItem>
                    ))}
                  </Menu>
                  <Menu>    
                    {menuItems.filter((a)=> {return a.fields.position === 'Right'}).map((e,i) => (
                    <MenuItem key={i} image={`https:${e.fields.icon.fields.file.url}`} href={e.fields.link} isActive={true} >  </MenuItem>  
                  ))}
                  </Menu>
                  <div >
                   <Image src={`https:${hamburgerMenu}` } alt="Vercel Logo"  height={16} width={16} />
                   </div>
              </div>
          </div>
          
          <div >
              {heroImage && <Image src={`https:${heroImage}` } alt="Vercel Logo" layout='fill' />}
          </div>

      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
         
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
         
        </a>
      </footer>
    </>
  )
}


export async function getStaticProps() {
//  export async function getServerSideProps() {
  const client = createClient({
      space: process.env.CONTENTFUL_SPACE || '',
      accessToken: process.env.CONTENTFUL_ACCESS_TOKEN || ''
  })
  console.log(`Token: ${process.env.CONTENTFUL_ACCESS_TOKEN}`)
  const topBar = await client.getEntries({
    'fields.visible': 'true',
    content_type: 'topBar',
  })
  const menu = await client.getEntries({
    'fields.visible': 'true',
    content_type: 'menu',
  })
  const iconLibrary = await client.getEntries({
    
    content_type: 'iconLibrary',
  })


  return {
    props:{
      topBar: topBar.items,
      menu: menu.items,
      iconLibrary: iconLibrary.items,
      
    }
  }
}


export default Home
